apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ghcr.io/gerardbulky/github-actions-workflow/node-app:latest
          ports:
            - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: node-app  
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort
