apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

images:
  - name: ghcr.io/gerardbulky/github-actions-workflow/node-app
    newTag:  # This will be updated in the pipeline
